### ISSUE TITLE
removeCore permission denied

### ISSUE THREAD

**Issue by projectweekend** [spark/sparkjs#28]
I am authenticating using the access token method (`spark.login( { accessToken: "blahblahblah" } );`). When I call `spark.removeCore` I get a permission denied error.

**Comment by dmiddlecamp** [comment]
Hi @projectweekend,

  Are you still seeing this issue?

Thanks,
David

**Comment by projectweekend** [comment]
Yes. Very sorry for lack of a response. This is no longer an issue.

**Comment by dmiddlecamp** [comment]
No worries, thanks!  :+1:
