### ISSUE TITLE
Setup wifi details

### ISSUE THREAD

**Issue by moazam1** [spark/sparkjs#37]
Is it possible to setup wifi details in the core by using this library?

**Comment by emilyrose** [comment]
hey @moazam1! if this is still something you'd like to accomplish programmatically, let me know. I'm happy to help!

**Comment by moazam1** [comment]
Hi @emilyrose would love to know how to accomplish this task.

Cheers!

**Comment by emilyrose** [comment]
@moazam1, awesome!

One thing to mention first is that you will need to either manually hold the MODE button for 3 seconds to put it into 'listening' mode (blinking blue), or modify your Core to allow you to put it into listening mode programmatically (more on that if you're interested).

For the code itself, take a look at this function from the [spark-cli](https://github.com/spark/spark-cli):

https://github.com/spark/spark-cli/blob/master/js/commands/SerialCommand.js#L347-L433

As you can see, the configuration of WiFi happens over a serial port when connected to your computer.
The sequence for providing updated WiFi credentials for your Core is as follows:

* `w` — tells the Core you want to configure WiFi
* `<ssid>` — the SSID of the WiFi network
* `<security type>` — 0, 1, 2, or 3 (see below)
* `<password>` — password for the WiFi (if any)

Security type:
* 0 — no security
* 1 — WEP
* 2 — WPA-PSK
* 3 — WPA2-PSK

As for the serial port, on a *nix environment you will find it in `/dev` listed as a tty. On my Macbook for example, it shows up as `/dev/tty.usbmodem1451`.

I can even configure the WiFi directly through the serial port:

* Execute: `screen /dev/tty.usbmodem1451 115200` 
* type `w`
* follow the prompts, but don't mess up!

_NOTE: 115200 is the baud rate for the serial port_
_NOTE: your actual device name may vary from `tty.usbmodem1451`_

The drawback here is that by typing directly into the serial port, you can't undo any mistakes.

I hope this helps you in your quest for programmatic WiFi configuration! I'd love to see what you end up building. Let me know if you'd like to further discuss how you can put your Core into DFU mode without manually pressing the button (_HINT: it includes soldering and a second Core_).

**Comment by moazam1** [comment]
Thanks @emilyrose for the detailed information on how to setup wifi over serial. I already took code from spark-cli and built desktop apps for windows and mac. It works perfect. What we want now is to setup wifi details without connecting device to a computer. I have already checked Java applet solution but it's not working for us.
