### ISSUE TITLE
`getEventStream` throws "Bad callback given: undefined"

### ISSUE THREAD

**Issue by willwhitney** [spark/sparkjs#39]
Using any of the `spark.getEventStream` examples from the docs, e.g.

```javascript
spark.getEventStream(false, 'mine', function(data) {
  console.log("Event: " + data);
});
```

 results in this error:

```javascript
"Error: Bad callback given: undefined
    at request (chrome-extension://fbpknjbdgcpahjemekijemfgpckpiopg/lib/spark.min.js:1:22758)
    at SparkApi.getEventStream (chrome-extension://fbpknjbdgcpahjemekijemfgpckpiopg/lib/spark.min.js:1:6656)
    at Spark.getEventStream (chrome-extension://fbpknjbdgcpahjemekijemfgpckpiopg/lib/spark.min.js:1:20977)
    at <anonymous>:2:7
    at Object.InjectedScript._evaluateOn (<anonymous>:762:137)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:695:34)
    at Object.InjectedScript.evaluate (<anonymous>:609:21)"
```

This `spark` instance is logged in and has an access token.

Edit: using `device.subscribe` has the same error.

The error comes from `SparkApi.prototype.getEventStream` not passing the callback to `request`, which then throws.

**Comment by 8026787** [comment]
+1

**Comment by clarity99** [comment]
+1 - events are unusable from JS at this point?

**Comment by georgealways** [comment]
+1

**Comment by towynlin** [comment]
This has been deployed to npm, bower, and CDNs.

**Comment by willwhitney** [comment]
Thanks, Doc!

**Comment by georgealways** [comment]
Still no dice on this -- both the current version from the CDN and the distro I built from head (which actually differs than the distro that's currently checked in) both throw the same error for getEventStream:

```js
spark.login( { username: user, password: pass }, function() {
        spark.getEventStream( false, 'mine', function( data ) {
        console.log( "Event: " + data );
    } );
} )
```

```
Uncaught TypeError: undefined is not a function @spark.min.js:1 
Spark._createStreamProcessor.Processor.watch @spark.min.js:1 
Spark.getEventStreamarrow2.html:103 (anonymous function) @spark.min.js:1 
Spark.emitAndCallback @spark.min.js:1 
(anonymous function) @spark.min.js:1 
on_end @spark.min.js:1 
on_state_change @spark.min.js:1
```

**Comment by osresearch** [comment]
I get the same error when I call `device.subscribe()` as shown in the docs.

    > device
    Device {_spark: Spark, attributes: Object, id: "54ff6a066667515117431567", name: "matrix", lastApp: null…}
    > device.getVariable("read_adc").then(function(data) { console.log(data.result) })
    Promise {_handler: Pending, then: function, catch: function, _beget: function, spread: function…}
    564
    > device.subscribe("adc", function(data) { console.log(data) })
    spark.min.js:1 Uncaught TypeError: undefined is not a function
    Spark._createStreamProcessor.Processor.watch spark.min.js:1
    Spark.getEventStream spark.min.js:1
    Device.subscribe

**Comment by willwhitney** [comment]
As others have mentioned, and as documented in #49, this is still an issue.

**Comment by emilyrose** [comment]
if anyone has specific steps to reproduce, that would be fabulous!

**Comment by willwhitney** [comment]
Literally any of the examples in the docs crashes in the browser.

![screen shot 2015-03-06 at 4 36 06 pm](https://cloud.githubusercontent.com/assets/597829/6536940/df69fb1e-c41f-11e4-9718-9958939d635b.png)

![image](https://cloud.githubusercontent.com/assets/597829/6536922/bff5fe0e-c41f-11e4-9bca-d2b3c31420f1.png)

This is with a copy of spark.js downloaded from CDN just now, running latest Chrome.
