### ISSUE TITLE
Modal CSS interferes with frameworks

### ISSUE THREAD

**Issue by emcniece** [spark/sparkjs#45]
The `.modal` class injected through the inline CSS conflicts with a lot of frameworks. Requesting the ability to disable this injection, or requesting modifying the JS to use a more targeted spark-specific class.

**Comment by greatwitenorth** [comment]
Is there any status on this? It's messing up modals when using the ionic framework as well.

**Comment by emcniece** [comment]
Appears to be included as a fix in [Sprint 28](https://github.com/spark/sparkjs/milestones/Sprint%2028%20)

**Comment by emilyrose** [comment]
@greatwitenorth @emcniece hey! 

Have either of you tested out the changes in #46? I haven't yet had the chance to test it myself, so a simple test case would be super helpful if either of you would be willing to share!

Thanks!

**Comment by emcniece** [comment]
Haven't tested the JS changes against a compile or build tool, but the modified scripts are alive and well at http://spark-angular-starter-demo.herokuapp.com/#/tab/spark/cores . Add a new core - the modal that pops up has a "modal" class, styled by Ionic. See http://spark-angular-starter-demo.herokuapp.com/assets/lib/spark/dist/spark.js for the modified JS.

**Comment by emilyrose** [comment]
so taking another look at this, I'm not sure I like the idea of merging a patch to what should be a standard copy of jquery.modal.js. This could be mysterious and problematic down the road.

**Comment by emilyrose** [comment]
I did find this in the process of investigating:

https://github.com/kylefox/jquery-modal

Apparently you can set the class of the modal element you want to use! 
I think this is a much better way to go about it.

**Comment by emcniece** [comment]
... what? This is exactly what jquery.modal allows...

OH, fml. This doesn't require modifying jquery.modal.min.js.

The modal init happens in spark.js - if you view-source on view-source:http://spark-angular-starter-demo.herokuapp.com/assets/lib/spark/dist/spark.js it happens on line 9339. Changing the `modalClass` param should be sufficient and we can leave jquery.modal alone... 

I was just overzealous in my string-replace.

**Comment by emcniece** [comment]
I'll see if I can reroll a PR in the next day or two.

**Comment by emilyrose** [comment]
I've actually got one coming!

**Comment by emilyrose** [comment]
check out #53

**Comment by emcniece** [comment]
SUPER COOL. Sorry for all the confusion - nice work!

**Comment by emilyrose** [comment]
@emcniece not a problem at all! 

Your code changes were great in that they helped me see exactly what the issue was!

Thanks :smile_cat: I'm glad I could help.
