### ISSUE TITLE
some users still reporting 'undefined is not a function' when using getEventStream

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/sparkjs#49]

**Comment by dmiddlecamp** [comment]
spark.getEventStream(false, false, function(data) {
			  console.log("Event: " + data);
			});

![screen shot 2015-02-05 at 10 13 15 pm](https://cloud.githubusercontent.com/assets/833793/6074448/38c04248-ad84-11e4-82e3-c4b9cf44d661.png)

**Comment by jme783** [comment]
Having this issue as well +1

**Comment by towynlin** [comment]
Here's the function that actually has callback undefined:
https://github.com/spark/sparkjs/blob/master/lib/spark.js#L662-L668

**Comment by towynlin** [comment]
I think it's `onDataReady` vs `onData` as typo..

**Comment by emilyrose** [comment]
@towynlin good eye!

**Comment by suhajdab** [comment]
+1

**Comment by dmiddlecamp** [comment]
Fixed in 4204b5a3c17c4d92963eb23aa8e5c2038107bcf0
