### ISSUE TITLE
Get Event Stream timing out

### ISSUE THREAD

**Issue by nmccann** [spark/sparkjs#52]
Hi,

I'm using Spark.js on a Node.js server. On start-up I attempt to login with Spark.js, and if that is successful I register for a specific event for my own devices. This looks like the following:

```
sparkService.login({
            username: SPARK_USERNAME,
            password: SPARK_PASSWORD
        }, function (error, body) {
            sparkService.getEventStream("state_changed", "mine", function (data) {
               //Do something with contents of data
            })
        })
```

After roughly 10 minutes, I find that the `data` passed into my callback is `null`. I added a check to ensure this didn't crash my server, but I eventually noticed that once the `null` was received I didn't receive any further events. I was hesitant to declare this a Spark.js issue, since I was able to recreate the same issue with the Spark CLI - `spark subscribe mine`, after roughly 10 minutes it exits the command and no further events are logged. So I thought this might be expected, however I couldn't find any info on Spark's Cloud API to verify the timeout is intentional.

Now because of the length of time needed before a timeout, this has been difficult to rigorously test. It doesn't seem like the timeout is related to a lack of activity, however most of the time I just emit no events because that doesn't require action on my part. If someone can verify this behaviour isn't intentional, I will try to update my Core's firmware to create a better test case.

Since I get a `null` when it "times out" (or whatever it's doing), I should be able to workaround the issue by initiating a new `getEventStream`. Perhaps I'm misinterpreting how event streams should be used, maybe the web hook API would be better suited to the kinds of long running functionality I want.

Thank you for your assistance,
Noah

Note: This may be related to Issue #49

**Comment by towynlin** [comment]
I suspect you might be seeing the API worker to which you're connected restarting. This is common in large distributed computing systems like the Spark Cloud — see Erlang's "let it crash" philosophy as discussed, for example, [here](http://stackoverflow.com/questions/4393197/erlangs-let-it-crash-philosophy-applicable-elsewhere). We'd love to have these streams run forever—and you can be confident we keep working to push the stream life upward—but in reality you should gracefully handle stream closure, reconnecting the event stream when necessary. :smile: 

I'm closing the issue, but if you can point us to a specific cause for the null event, we'll definitely welcome the forensic help, reopen the issue, and tackle it head-on!

**Comment by towynlin** [comment]
Also, as you say, webhooks might make your life easier — we'll be releasing that to the public really soon!
