### ISSUE TITLE
Browser timeout in getEventStream after 3 minutes

### ISSUE THREAD

**Issue by emilyrose** [spark/sparkjs#55]
![image](https://cloud.githubusercontent.com/assets/617235/6581632/78e2aa96-c715-11e4-8209-07ec201cae13.png)

Steps to reproduce:
* Use version 0.4.1
* Call getEventStream
* Wait 3 minutes

For example:

```js
spark.getEventStream(false, false, function(dat) {
	console.log(dat);
})
```

**Comment by dmiddlecamp** [comment]
I'm guessing it's either taking up too much space, or hitting some timeout.

**Comment by emilyrose** [comment]
yeah I think the error is pretty explicit here, "ETIMEDOUT".

**Comment by dmiddlecamp** [comment]
Hah, sorry! :)  :+1:

**Comment by emilyrose** [comment]
The troubling thing is that the error doesn't always happen. Sometimes it just silently drops out. :'(

**Comment by jme783** [comment]
+1 on this, experiencing this on my side as well

**Comment by emilyrose** [comment]
I don't really see a quick fix for this (aside from short-circuiting the timeout and just force-restarting the stream every <3 minutes, which is 'terribly hacky' at best).

**Comment by towynlin** [comment]
We should automatically restart the stream anytime it fails, but do an exponential back off rather than hammer over and over if something's down.

**Comment by emilyrose** [comment]
@towynlin agreed. My main concern right now is that so far in my trials the actual ETIMEDOUT error is only firing about 1 in 3 times.

**Comment by towynlin** [comment]
I suspect that if one lets the stream run forever, it will always eventually close. :smiling_imp:
