### ISSUE TITLE
logging in with an access token does not validate that token

### ISSUE THREAD

**Issue by willwhitney** [spark/sparkjs#59]
If you use the `spark.login({accessToken: 'ACCESS_TOKEN'})` method of login, it should check to make sure that the token you're using is valid.

**Comment by towynlin** [comment]
Valid in this case means the following.

```js
function isValidAccessToken(token) {
  return /[0-9a-f]{40}/.test(token);
}
```

where lower case is in fact required.

**Comment by willwhitney** [comment]
Sure, I'm just pointing out that's somewhat misleading, in that tokens may
not *still be valid*, e.g. expired. This means that it's not actually
possible to check that a token still works without trying to use it and
just attempting to catch when it crashes.

This caused a bug in a project for me.

Plus, which seems like a more common situation: you have a saved token, but
it somehow became no longer a length-40 b64 string, or that it expired?

**Comment by towynlin** [comment]
Ah! No, no, my confusion on what you by "valid", which was why I was clarifying. Much more common to have an expired token. Calling `spark.login` with an access token doesn't actually hit the cloud at all.

I don't know whether sparkjs gets a new token when an existing one fails _and_ we have a username and password. It should if it doesn't.

@willwhitney If you call login with an access token, and you have not passed a username and password, all sparkjs can do is fail, which is the same whether at login or on some later call. What would you like the behavior to be? What would have helped the most with your project debugging?

**Comment by willwhitney** [comment]
It would be a huge improvement for it to fail immediately and exactly the
same way as if you've called `spark.login` with a username and password.
Since the methods are called the same thing, they should behave the same
way.

Here's what a normal application flow looks like:
1. Start
2. Check to see if you have a token and that it works
3. If you don't, or it doesn't, display a login page to the user
4. Get a working token
5. Profit!

If there's not a way to explicitly check this, then you have to write extra
code to hit some random other endpoint of your choosing to check that the
token works. If you don't check the token ahead of time, you're going to
render the UI first, then fail back out to login, which is a very weird
user experience.

**Comment by towynlin** [comment]
Oh! And you're talking primarily about the browser, whereas I was thinking primarily about node.

Overall :+1:

Make sense to you @emilyrose?

Thanks for the suggestion @willwhitney — because we're focused on Photon delivery right now, I imagine this will get on the priority list some time in May.

**Comment by willwhitney** [comment]
Great, thanks!

**Comment by emilyrose** [comment]
@towynlin thanks for the ping!

@willwhitney this totally makes sense. I had the same kind of confusion you described with an expired token. I think your suggestion sounds like a reasonable way to approach a fix for this!

Thanks!

**Comment by lourd** [comment]
@towynlin As far as this goes on Node, we'd also really like if calling `Spark.login` with an access token actually pinged the cloud and verified it, throwing an error if it's not a valid token. That way, if our main program starts with a `login` call, it'll fail up front instead of continuing on and trying to call a bunch of stuff that will fail.

I'm happy to PR this, but I'm not sure what endpoint I would use on the Cloud API to just verify a token.

**Comment by towynlin** [comment]
Hm, we don't have any particular endpoint perfectly suited to just checking token validity. Off the top of my head `GET /v1/devices` seems best, as in `spark.listDevices`. :+1:

**Comment by lourd** [comment]
Unless you have a few hundred/thousand/tens of thousnads devices?

**Comment by monkbroc** [comment]
@towynlin @dmiddlecamp I think it would be good to add a `GET /v1/access_tokens/id` endpoint to get the attributes of a token. Right now, you get those attributes when you create a token, or when you list all tokens, but you can't request attributes for a single token.

**Comment by dmiddlecamp** [comment]
:+1:

**Comment by brycekahle** [comment]
In `particle-api-js` the library does not cache the token, you specify the token for each call.
