### ISSUE TITLE
Get multiple instances of the Spark object

### ISSUE THREAD

**Issue by blitzxion** [spark/sparkjs#60]
Reviewing the source of this tool and at the following line:
https://github.com/spark/sparkjs/blob/master/lib/spark.js#L47

I would like to be able to make additional instances of the spark object (in effort for multiple login access, etc). I've tried passing new token's into the login, but when dealing with events, it sometimes causes issues.

For example:
```javascript

var sparkA = new Spark();
var sparkB = new Spark();

sparkA.login({accessToken:"TokenA"});
sparkB.login({accessToken:"TokenB"});

// etc, etc...
sparkA.getEventStream(/*...*/);
sparkB.getEventStream(/*...*/);

```

But, as the examples in this repo show, you can only get one instance:

```javascript

 // Because of the browserify encapsulation, and the only available property is window.spark
var sparkA = spark;

// etc, etc

```

Right now, the only way for me to get multiple instances of the spark object is to use jQuery's extend (deep copy):

```javascript

var sparkA = jQuery.extend(true, {}, spark);
var sparkB = jQuery.extend(true, {}, spark);

// etc, etc

```
I'm sure using jQuery's deep copy is far from efficient, but I'm left with no alternative (that I know of) without modifying the original source. 

Can I get some additional input on this matter, or maybe an alternative approach?

**Comment by emilyrose** [comment]
This is something that will be addressed in a future version of the library. Please feel free to re-open if you'd like to discuss this further!
