### ISSUE TITLE
Signal call doesn't work because of missing Access-Control-Allow-Origin:*

### ISSUE THREAD

**Issue by GeertWille** [spark/sparkjs#62]
Access-Control-Allow-Origin:* is missing in the response header of the Signal call...

XMLHttpRequest cannot load https://api.spark.io/v1/devices/[device_id]. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://my-domain.com' is therefore not allowed access. The response had HTTP status code 400.

**Comment by dmiddlecamp** [comment]
Hmm, it should be present for every endpoint, are you sure?  I just tested this and got the CORS headers back correctly

**Comment by GeertWille** [comment]
```spark.signalCore('54ff70066672524812511067', true).then(
function(success){console.info(success)}, function(err){console.info(err)})```

**Comment by GeertWille** [comment]
`spark.signalCore('coreid', true).then(function(success){console.info(success)}, function(err){console.info(err)})` 

returns 

`Error: CORS request rejected: https://api.spark.io/v1/devices/54ff70066672524812511067`

All the other calls are working just that one gives me this error...

**Comment by dmiddlecamp** [comment]
Hmm, that's really weird.  Can you tell me anything extra about your setup?  What versions of the modules do you have, are you running on localhost or on a site?

**Comment by GeertWille** [comment]
I am testing on localhost, i'll try on my server and let you know what it does there. I am using v0.4.2 of the script from [here](//cdn.jsdelivr.net/sparkjs/0.4.2/spark.min.js). Anything else you need to know? If it matters my core uses the feature/hal branch but I guess that doesn't matter because the problem occurs before even reaching the core of course...

**Comment by brycekahle** [comment]
@GeertWille can you test again. I just confirmed it is added to all responses.
