### ISSUE TITLE
Changelog needed

### ISSUE THREAD

**Issue by lourd** [spark/sparkjs#64]
I know there's the Release History section at the bottom of the README, but a separate CHANGELOG.md or History.md or just more thorough release notes would be really great. Please and thank you!

Also, a category on the forums for API clients with sub categories for each language would be awesome as well. I guess it's just Javascript for now, but thinking ahead if other languages are implemented

**Comment by emilyrose** [comment]
@lourd this is definitely happening soon as part of our transition of this library to ParticleJS! Thanks for the suggestion!
