### ISSUE TITLE
SparkJS should point at api.particle.io

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/sparkjs#71]
I think CORS headers are broken by the redirect, we should fix this and issue a release ASAP

```
  this.baseUrl = 'https://api.spark.io';
```

Thanks!
David

**Comment by joegoggins** [comment]
There is not currently a redirect for https://api.spark.io, it is supposed to function interchangeably with api.particle.io for the time being. Could you elaborate on the issue you're seeing?

**Comment by dmiddlecamp** [comment]
Hmm, maybe I'm going crazy then... I've been getting reports from some community members of CORS errors in SparkJS, and seeing the old domain was a red flag for me, maybe it's a different issue?

**Comment by joegoggins** [comment]
Yea, :100: :+1: on changing the name to api.particle.io, can't go wrong.

Perhaps this change will knock those CORS issues too--you would get errors if some code paths were using api.spark.io and others were using api.particle.io...could be a source of the problem.

**Comment by emilyrose** [comment]
:+1:, will do.

**Comment by emilyrose** [comment]
done! :smile_cat:
