### ISSUE TITLE
getEventStream stops returning events after a long time

### ISSUE THREAD

**Issue by dgmltn** [spark/sparkjs#72]
I have a motion detector attached to my spark core, that outputs events like:

```
Spark.publish("motion-detected", NULL, 60, PRIVATE);
```

I'm using this script to monitor it:

> https://github.com/dgmltn/pimatic-particle/blob/master/test-eventstream.js

It stops logging events after a long time (after a day or two). I noticed the same issue when using the EventSource js module instead of the official sparkjs module. I know it's a problem with the client, because if I restart the client script, it continues chugging along.

**Comment by lourd** [comment]
Not that this is a fix, but you can explicitly restart it if it gets an end event. This is in some of the examples:

```js
function openStream() {
  const req = Spark.getEventStream( false, 'mine', function(...) {...}  );
  req.on('end', function() {
    console.warn("Spark event stream ended! re-opening in 3 seconds...");
    setTimeout(openStream, 3 * 1000);
  });
}
```

**Comment by mfferreira** [comment]
Bump.

Is there a way to explicitly kill the current stream?

**Comment by lourd** [comment]
`Spark.getEventStream` returns an instance of [`Request`](https://www.npmjs.com/package/request). I thought closing it was as simple as calling `end` or `destroy` but having played around with that in the debugger neither of those actually work... :question: 

This is the key snippet I was using in conjunction with Node Inspector to play around.

```js
  const stream = particle.getEventStream(false, 'mine', handler);

  // Sometimes the stream ends, we want to be sure to restart it
  stream.on('end', () => {
    console.log('Particle event stream ended! Restarting in 3 seconds...');
    // TODO track the stream closing event
    setTimeout(openEventStream, 3000);
  });

  setTimeout(() => {
    const s = stream;
    debugger
    // Calling s.end() did nothing to stop the stream, earlier event listener was not fired
    // Calling s.destroy() did nothing to stop the stream
  }, 10000)
```

**Comment by brycekahle** [comment]
Give `abort` a try.

**Comment by lourd** [comment]
Yeah, that did the trick. What the hell, how is that not documented in the Node [Stream API](https://nodejs.org/api/stream.html)?

**Comment by brycekahle** [comment]
`request` doesn't return a stream but a `Request` object. It is a `request` method.

**Comment by lourd** [comment]
Right. Well, not documented in their API either :confused: [Here's the open issue asking for it](https://github.com/request/request/issues/1670)

**Comment by mfferreira** [comment]
Great. Thanks @brycekahle
