### ISSUE TITLE
Processor.processItem failing: Syntax Error: Unexpected end of input

### ISSUE THREAD

**Issue by lourd** [spark/sparkjs#77]
We see this error anywhere from 3-10 times/week right now:

```sh
W20150814-18:28:34.135(-4)? (STDERR)  {"data":"1,-50.0","ttl":
W20150814-18:28:34.135(-4)? (STDERR)                          ^
W20150814-18:28:34.137(-4)? (STDERR) SyntaxError: Unexpected end of input
W20150814-18:28:34.137(-4)? (STDERR)    at Object.parse (native)
W20150814-18:28:34.137(-4)? (STDERR)    at Object.Spark._createStreamProcessor.Processor.processItem (.../node_modules/spark/lib/spark.js:679:32)
W20150814-18:28:34.137(-4)? (STDERR)    at Object.Spark._createStreamProcessor.Processor.appendToQueue (.../node_modules/spark/lib/spark.js:663:26)
W20150814-18:28:34.137(-4)? (STDERR)    at Object.Spark._createStreamProcessor.Processor.onData (.../node_modules/spark/lib/spark.js:690:18)
W20150814-18:28:34.137(-4)? (STDERR)    at Request.emit (events.js:117:20)
W20150814-18:28:34.138(-4)? (STDERR)    at IncomingMessage.Request.onRequestResponse.strings (.../node_modules/spark/node_modules/request/request.js:1000:12)
W20150814-18:28:34.138(-4)? (STDERR)    at IncomingMessage.emit (events.js:95:17)
W20150814-18:28:34.138(-4)? (STDERR)    at IncomingMessage.<anonymous> (_stream_readable.js:765:14)
W20150814-18:28:34.138(-4)? (STDERR)    at IncomingMessage.emit (events.js:92:17)
W20150814-18:28:34.138(-4)? (STDERR)    at emitReadable_ (_stream_readable.js:427:10)
```

What would be the right way to handle this? The `JSON.parse` statement at https://github.com/spark/sparkjs/blob/master/lib/spark.js#L679 needs a `try-catch` block, but what should happen with the error when it's caught? Just log it?

**Comment by towynlin** [comment]
Since the subscription is an ongoing TCP stream, we don't have control over where the packet boundaries and node.js data stream chunks are. In this case you're getting a chunk of data ending with an incomplete line; the next chunk in the stream should contain the rest. You should wait to receive more data, and then retry that same incomplete line again. Make sense?

**Comment by lourd** [comment]
Yup. It looks like [this](https://github.com/spark/sparkjs/blob/master/lib/spark.js#L676) check isn't correct under certain conditions. It's expecting that the JSON object does come in as one whole chunk and it starts with `data:`. Any thoughts on what the correct condition would be?

**Comment by lourd** [comment]
Do you think there should still be a try-catch block just in case, instead of crashing the program?

**Comment by towynlin** [comment]
Thanks, yep, exactly — the `JSON.parse` should have a try-catch block. In the catch block, we should save the value of `line` (after the "data:" has been removed) and when we receive our next chunk, prepend the saved value to the new chunk.

**Comment by towynlin** [comment]
And also, as you point out, it would be possible to get just, for example, "da" instead of "data:" or "eve" instead of "event:". We would also need to save the incomplete text in these cases.

**Comment by lourd** [comment]
@towynlin your suggestions sound spot on. Do you think y'all will work on implementing that fix soon or is it on us?

**Comment by emilyrose** [comment]
@lourd this isn't on my list of current objectives, but it seems like an important fix so I will add it to our internal issue tracker!

**Comment by towynlin** [comment]
@lourd Given how hard we're working on the Electron right now, I suspect this will happen faster if you take it on. Think you could manage it?

**Comment by lourd** [comment]
I think so, the fix sounds pretty straightforward. I'm not sure how I'd write a reproduction of the bug as a test to make sure it's actually solved though. Any suggestion intentionally splitting event data between TCP messages?
