### ISSUE TITLE
listWebhooks function definition incorrect

### ISSUE THREAD

**Issue by steelydev** [spark/sparkjs#80]
Spark.prototype.listWebhooks = function(callback) 

should be 

        Spark.prototype.listWebhooks = function(accessToken, callback) 

I think.

**Comment by brycekahle** [comment]
The `accessToken` is stored on the `spark` object. Is it expecting you to call `login` first before calling any other methods. Check out https://docs.particle.io/reference/javascript/#logging-in for more information.
