### ISSUE TITLE
Promise interface on the device object

### ISSUE THREAD

**Issue by paulovieira** [spark/sparkjs#82]
I tried your API using ParticleJS and everything worked very well. Congratulations on your product!

But one thing that I found missing is the fact that the methods in the `device` object don't return promises. The docs say "`You can interact with the api using callbacks, events or promises`", but promises seem to be available only for method in the `spark` object. 

Is this an intentional API design, or something that not implemented yet? It makes the current API a bit incoherent.

**Comment by brycekahle** [comment]
Was there a specific method you were trying to use? The device object just proxies to the main API module for most operations which supports promises. This could just be a bug.

**Comment by brycekahle** [comment]
It looks like #81 might solve your problem.
